sudo: required
services:
  - docker

before_install:
  - docker build -t mohesk/docker -f ./client/Dockerfile.dev ./client

script:
  - docker run mohesk/docker npm run test -- --coverage
  
after_success:
  - docker build -t mohesk/docker-client ./client
  - docker build -t mohesk/docker-nginx ./nginx
  - docker build -t mohesk/docker-server ./server
  - docker build -t mohesk/docker-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mohesk/docker-client
  - docker push mohesk/docker-nginx
  - docker push mohesk/docker-server
  - docker push mohesk/docker-worker

